{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (task_group) (nomad_nomad_job_summary_running{exported_job=~\"(presence|homebase|go-links)\"})",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Cluster components memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) (process_resident_memory_bytes{job=~\"(consul-agent|nomad-agent|vault)\",node_name=~\".+\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node available memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (node_hwmon_temp_celsius)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Raspberry Pi fan state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_cooling_device_max_state", "legendFormat": "{{node_name}}" },
    { "expr": "node_cooling_device_cur_state", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "Ethernet egress rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])*8)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "UPS battery health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "min(tripplite_health)" }
   ]
  }
 ]
}