- name: Install nut package
  package:
    name: nut
    state: present

- include_tasks: linux.yml
  when: ansible_system == "Linux"

- include_tasks: freebsd.yml
  when: ansible_system == "FreeBSD"
