{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (app) (up{app=~\"(detect-presence|homebase|go-links|homebase-bot)\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Kube API server memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-apiservers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node available memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Who is the leader?",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])*8)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UPS battery health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "min(tripplite_health)" }
   ]
  }
 ]
}