{
 "title": "Envoy",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,consul_source_namespace)"
   },
   {
    "name": "Service",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,consul_source_service)"
   }
  ]
 },
 "panels": [
  { "title": "DownStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m])) by (consul_source_service)",
     "legendFormat": "{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m])) by (consul_source_service)",
     "legendFormat": "{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, service))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, service))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, service))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (consul_source_service)",
     "legendFormat": "{{consul_source_service}}"
    }
   ]
  },
  { "title": "Drill down to cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service Total",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (service)"
    },
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Upstream RPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}[1m])) by (consul_source_service,consul_source_namespace)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}[1m])) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_source_service=~\"$Service\",consul_source_namespace=~\"$Namespace\"}[1m])) by (le, consul_source_service, consul_source_namespace))",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_source_service=~\"$Service\",consul_source_namespace=~\"$Namespace\"}[1m])) by (le, consul_source_service, consul_source_namespace))",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_source_service=~\"$Service\",consul_source_namespace=~\"$Namespace\"}[1m])) by (le, consul_source_service, consul_source_namespace))",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  { "title": "UpStream x", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Upstream 2xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\",envoy_response_code_class=~\"2\"}[1m])) by (consul_source_namespace,consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\",envoy_response_code_class=\"3\"}[1m])) by (consul_source_namespace,consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\",envoy_response_code_class=\"4\"}[1m])) by (consul_source_namespace,consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\",envoy_response_code_class=\"5\"}[1m])) by (consul_source_namespace,consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Endpoint Percentage Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service) / avg(envoy_cluster_membership_total{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service) - avg(envoy_cluster_membership_healthy{consul_source_namespace=~\"$Namespace\",consul_source_service=~\"$Service\"}) by (consul_source_namespace, consul_source_service)",
     "legendFormat": "{{consul_source_namespace}}/{{consul_source_service}}"
    }
   ]
  }
 ]
}