{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Is Matt home?",
   "type": "stat",
   "description": "This will say \"No\" if any devices are not present, on the assumption that my devices can't leave the house without me, so if any are gone, I'm definitely out of the house.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(presence_device_total)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(presence_device_total) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - presence_last_leave_timestamp",
     "legendFormat": "Last left"
    },
    {
     "expr": "time() - presence_last_return_timestamp",
     "legendFormat": "Last returned"
    },
    {
     "expr": "presence:trip_duration_seconds:last",
     "legendFormat": "Last trip duration"
    },
    {
     "expr": "presence:trip_duration_seconds:current",
     "legendFormat": "Current trip duration"
    }
   ]
  },
  {
   "title": "Bluetooth device health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presence_bluetooth_healthy" }
   ]
  },
  {
   "title": "Device check durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(presence_device_check_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(presence_device_check_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": { "content": "# History" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Past 24 hours",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presence_device_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "1 day ago",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presence_device_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "2 days ago",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presence_device_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"detect-presence/detect-presence\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "# Alerts\n\nThe graph below only exists to power alerts.\n\n"
   },
   "content": "# Alerts\n\nThe graph below only exists to power alerts.\n\n"
  },
  {
   "title": "Device presence alerts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presence_device_total", "legendFormat": "{{name}}" }
   ]
  }
 ]
}