---
ansible_host: artemis.homelab

default_ip: 10.0.2.10
tailscale_ip: 100.75.195.24

setup_pf: true

consul_services:
  - node_exporter
  - named-local
  - bind_exporter-local
  - postgresql
  - minio
  - minio-console
  - prometheus
  - alertmanager
  - named-tailscale
  - bind_exporter-tailscale
  - redis
  - paperless
  - phabricator
  - mysql
  - teamcity
  - homelab
  - livebook
  - guacamole
