{
 "title": "Bind9 Exporter DNS",
 "description": "Bind9 DNS Service Statistics.",
 "tags": [
  "bind",
  "dns",
  "bind-exporter",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(bind_up, job)" },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(bind_up, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(bind_up{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_time_seconds{instance=\"10.0.2.10:9100\"}) - max(bind_boot_time_seconds{instance=~\"$node:.*\"}) "
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  {
   "title": "Reconfigured",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_time_seconds{instance=\"10.0.2.10:9100\"}) - max(bind_config_time_seconds{instance=~\"$node:.*\"})"
    }
   ]
  },
  { "title": "Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Incoming Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_responses_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Resolver Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / LAME"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / MISMATCH"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / TRUNCATED"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_queries_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / EDNS0"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / Retry"
    }
   ]
  },
  {
   "title": "Query By Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_duration_seconds_bucket{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ le }}"
    }
   ]
  },
  {
   "title": "Resolver Cache RR Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_resolver_cache_rrsets{instance=\"$node:$port\",job=\"$job\"}",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "DNSSEC Validation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / ValErr"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=\"$node:$port\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ result }}"
    }
   ]
  }
 ]
}