- name: Install Bastille
  package:
    name: bastille
    state: present

- name: Create templates directory
  file:
    path: /usr/local/bastille/templates/mjm
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Install pkg Bastille template
  copy:
    src: pkg/
    dest: /usr/local/bastille/templates/mjm/pkg
    owner: root
    group: wheel

- name: Install log Bastille template
  copy:
    src: log/
    dest: /usr/local/bastille/templates/mjm/log
    owner: root
    group: wheel

- name: Install consul-template Bastille template
  copy:
    src: consul-template/
    dest: /usr/local/bastille/templates/mjm/consul-template
    owner: root
    group: wheel
