- name: Install Bastille and Rocinante
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bastille
    - rocinante

- name: Copy bastille.conf
  copy:
    src: bastille.conf
    dest: /usr/local/etc/bastille/bastille.conf
    owner: root
    group: wheel
    mode: 0644

- name: Create templates directories
  file:
    path: /usr/local/{{ item }}/templates/mjm
    state: directory
    mode: 0755
    owner: root
    group: wheel
  loop:
    - bastille
    - rocinante

- name: Install Bastille templates
  copy:
    src: "{{ item }}/"
    dest: "/usr/local/bastille/templates/mjm/{{ item }}"
    owner: root
    group: wheel
  loop:
    - pkg
    - log
    - consul-template
    - vault-agent
    - pkg-server
    - log-server
    - redis
    - paperless
    - phabricator
    - livebook
    - teamcity
    - minio
    - prometheus
    - homelab
    - mysql
    - postgresql
    - znc
    - guacamole

- name: Install Rocinante templates
  copy:
    src: "{{ item }}/"
    dest: "/usr/local/rocinante/templates/mjm/{{ item }}"
    owner: root
    group: wheel
  loop:
    - pkg
    - log
