- name: Install Bastille
  package:
    name: bastille
    state: present

- name: Create templates directory
  file:
    path: /usr/local/bastille/templates/mjm
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Install Bastille template pkg
  copy:
    src: pkg/
    dest: /usr/local/bastille/templates/mjm/pkg
    owner: root
    group: wheel
