- name: Install Bastille
  package:
    name: bastille
    state: present

- name: Create templates directory
  file:
    path: /usr/local/bastille/templates/mjm
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Install Bastille templates
  copy:
    src: "{{ item }}/"
    dest: "/usr/local/bastille/templates/mjm/{{ item }}"
    owner: root
    group: wheel
  loop:
    - pkg
    - log
    - consul-template
    - redis
    - paperless
    - phabricator

