// Code generated by sqlc. DO NOT EDIT.
// source: links.sql

package database

import (
	"context"

	"github.com/segmentio/ksuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links
    (id, short_url, destination_url, description)
VALUES ($1, $2, $3, $4)
RETURNING id, short_url, destination_url, description, created_at, updated_at
`

type CreateLinkParams struct {
	ID             ksuid.KSUID
	ShortURL       string
	DestinationURL string
	Description    string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.ID,
		arg.ShortURL,
		arg.DestinationURL,
		arg.Description,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortURL,
		&i.DestinationURL,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentLinks = `-- name: ListRecentLinks :many
SELECT id, short_url, destination_url, description, created_at, updated_at
FROM links
ORDER BY created_at DESC
LIMIT 30
`

func (q *Queries) ListRecentLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.ShortURL,
			&i.DestinationURL,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
