// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"time"

	"github.com/segmentio/ksuid"
)

type Link struct {
	ID             ksuid.KSUID
	ShortURL       string
	DestinationURL string
	Description    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
