- name: Install necessary packages
  package:
    name: "{{ item }}"
    state: present
  loop: [py39-borgbackup, tarsnap]

- name: Create /opt/homelab directory
  file:
    path: /opt/homelab
    state: directory
    mode: 0700
    owner: root
    group: wheel

- name: Install deploy-homelab script
  copy:
    src: deploy-homelab.sh
    dest: /opt/deploy-homelab
    mode: 0755
    owner: root
    group: wheel

- name: Install start-homelab script
  copy:
    src: start-homelab.sh
    dest: /opt/start-homelab
    mode: 0755
    owner: root
    group: wheel
