- name: Set up Vault agent
  include_tasks: agent.yml
  when: vault_agent_enabled

- name: Set up Vault server
  include_tasks: server.yml
  when: vault_server_enabled

- include_tasks: bastille.yml
  when: inventory_hostname == 'artemis'
