- name: Install dns-server Bastille template
  copy:
    src: dns-server/
    dest: /usr/local/bastille/templates/mjm/dns-server
    owner: root
    group: wheel

- name: Install dns-server-local Bastille template
  copy: 
    src: dns-server-local/
    dest: /usr/local/bastille/templates/mjm/dns-server-local
    owner: root
    group: wheel

- name: Install dns-server-tailscale Bastille template
  copy: 
    src: dns-server-tailscale/
    dest: /usr/local/bastille/templates/mjm/dns-server-tailscale
    owner: root
    group: wheel

- name: Install local zone DB templates
  template:
    src: "{{ item }}.local.db.tpl.j2"
    dest: "/usr/local/bastille/templates/mjm/dns-server-local/{{ item }}.db"
    mode: 0644
    owner: root
    group: wheel
  loop: "{{ zone_names }}"

- name: Install tailscale zone DB templates
  template:
    src: "{{ item }}.tailscale.db.tpl.j2"
    dest: "/usr/local/bastille/templates/mjm/dns-server-tailscale/{{ item }}.db.tpl"
    mode: 0644
    owner: root
    group: wheel
  loop: "{{ zone_names }}"
