- hosts: artemis
  become: true
  roles:
    - role: pkg
    - role: logging
    - role: bastille
    - role: vault
    - role: nut
    - role: dns
    - role: consul
    - role: mail
    - role: ssl
