- hosts: freebsd
  become: true
  roles:
    - role: shell-tools
    - role: bastille
    - role: consul
    - role: dns
    - role: mail
    - role: ssh
    #- role: ssl

- hosts: daedalus
  become: true
  roles:
    - role: poudriere
