#!/bin/bash

set -e

cd "$(git rev-parse --show-toplevel)/ansible" || exit

tmpdir="$(mktemp -d)"
keypath="$tmpdir/signed-cert.pub"

function finish {
  echo "Cleaning up key in $tmpdir" >&2
  rm -rf "$tmpdir"
}
trap finish EXIT

vault write \
  -field=signed_key \
  ssh-client-signer/sign/homelab-client \
  "public_key=$(cat ~/.ssh/yubikey.pub)" \
  valid_principals=ubuntu,matt \
  >"$keypath"
echo "Generated temporary certificate key at $keypath" >&2

ansible-playbook --vault-password-file vault-password.sh --ssh-common-args="-i $HOME/.ssh/id_ed25519 -i $keypath" --inventory=hosts.ini "$@"

