#!/bin/bash

# In case this is being run from a random directory outside this repo
export VAULT_ADDR=http://vault.service.consul:8200

vault ssh \
  -mode="ca" \
  -role="homelab-client" \
  -mount-point="ssh-client-signer" \
  -private-key-path="${HOME}/.ssh/id_ed25519" \
  -public-key-path="${HOME}/.ssh/id_ed25519.pub" \
  -valid-principals="ubuntu" \
  "$@"
