#!/bin/sh

# In case this is being run from a random directory outside this repo
export VAULT_ADDR=http://vault.service.consul:8200

vault ssh \
  -mode="ca" \
  -role="homelab-client" \
  -mount-point="ssh-client-signer" \
  -public-key-path="${HOME}/.ssh/yubikey.pub" \
  -valid-principals="ubuntu,matt" \
  -no-exec \
  -field=signed_key \
  "$1" \
  >"${HOME}/.ssh/yubikey-cert.pub"

ssh -i "${HOME}/.ssh/yubikey-cert.pub" "$@"

