// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: detect-presence/proto/trips/trips.proto

package trips

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListTripsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTripsRequest) Reset() {
	*x = ListTripsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsRequest) ProtoMessage() {}

func (x *ListTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsRequest.ProtoReflect.Descriptor instead.
func (*ListTripsRequest) Descriptor() ([]byte, []int) {
	return file_detect_presence_proto_trips_trips_proto_rawDescGZIP(), []int{0}
}

type ListTripsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trips []*ListTripsResponse_Trip `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
}

func (x *ListTripsResponse) Reset() {
	*x = ListTripsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsResponse) ProtoMessage() {}

func (x *ListTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsResponse.ProtoReflect.Descriptor instead.
func (*ListTripsResponse) Descriptor() ([]byte, []int) {
	return file_detect_presence_proto_trips_trips_proto_rawDescGZIP(), []int{1}
}

func (x *ListTripsResponse) GetTrips() []*ListTripsResponse_Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

type ListTripsResponse_Trip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeftAt     string `protobuf:"bytes,2,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	ReturnedAt string `protobuf:"bytes,3,opt,name=returned_at,json=returnedAt,proto3" json:"returned_at,omitempty"`
}

func (x *ListTripsResponse_Trip) Reset() {
	*x = ListTripsResponse_Trip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTripsResponse_Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsResponse_Trip) ProtoMessage() {}

func (x *ListTripsResponse_Trip) ProtoReflect() protoreflect.Message {
	mi := &file_detect_presence_proto_trips_trips_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsResponse_Trip.ProtoReflect.Descriptor instead.
func (*ListTripsResponse_Trip) Descriptor() ([]byte, []int) {
	return file_detect_presence_proto_trips_trips_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListTripsResponse_Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListTripsResponse_Trip) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

func (x *ListTripsResponse_Trip) GetReturnedAt() string {
	if x != nil {
		return x.ReturnedAt
	}
	return ""
}

var File_detect_presence_proto_trips_trips_proto protoreflect.FileDescriptor

var file_detect_presence_proto_trips_trips_proto_rawDesc = []byte{
	0x0a, 0x27, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2d, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x73, 0x2f, 0x74, 0x72,
	0x69, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x72, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x94, 0x01,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x72, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x69, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x52, 0x05, 0x74, 0x72, 0x69,
	0x70, 0x73, 0x1a, 0x50, 0x0a, 0x04, 0x54, 0x72, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65,
	0x66, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x66,
	0x74, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x65, 0x64, 0x41, 0x74, 0x32, 0x42, 0x0a, 0x0c, 0x54, 0x72, 0x69, 0x70, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x69, 0x70,
	0x73, 0x12, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x69, 0x70, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_detect_presence_proto_trips_trips_proto_rawDescOnce sync.Once
	file_detect_presence_proto_trips_trips_proto_rawDescData = file_detect_presence_proto_trips_trips_proto_rawDesc
)

func file_detect_presence_proto_trips_trips_proto_rawDescGZIP() []byte {
	file_detect_presence_proto_trips_trips_proto_rawDescOnce.Do(func() {
		file_detect_presence_proto_trips_trips_proto_rawDescData = protoimpl.X.CompressGZIP(file_detect_presence_proto_trips_trips_proto_rawDescData)
	})
	return file_detect_presence_proto_trips_trips_proto_rawDescData
}

var file_detect_presence_proto_trips_trips_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_detect_presence_proto_trips_trips_proto_goTypes = []interface{}{
	(*ListTripsRequest)(nil),       // 0: ListTripsRequest
	(*ListTripsResponse)(nil),      // 1: ListTripsResponse
	(*ListTripsResponse_Trip)(nil), // 2: ListTripsResponse.Trip
}
var file_detect_presence_proto_trips_trips_proto_depIdxs = []int32{
	2, // 0: ListTripsResponse.trips:type_name -> ListTripsResponse.Trip
	0, // 1: TripsService.ListTrips:input_type -> ListTripsRequest
	1, // 2: TripsService.ListTrips:output_type -> ListTripsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_detect_presence_proto_trips_trips_proto_init() }
func file_detect_presence_proto_trips_trips_proto_init() {
	if File_detect_presence_proto_trips_trips_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_detect_presence_proto_trips_trips_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTripsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_presence_proto_trips_trips_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTripsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_presence_proto_trips_trips_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTripsResponse_Trip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detect_presence_proto_trips_trips_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detect_presence_proto_trips_trips_proto_goTypes,
		DependencyIndexes: file_detect_presence_proto_trips_trips_proto_depIdxs,
		MessageInfos:      file_detect_presence_proto_trips_trips_proto_msgTypes,
	}.Build()
	File_detect_presence_proto_trips_trips_proto = out.File
	file_detect_presence_proto_trips_trips_proto_rawDesc = nil
	file_detect_presence_proto_trips_trips_proto_goTypes = nil
	file_detect_presence_proto_trips_trips_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TripsServiceClient is the client API for TripsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TripsServiceClient interface {
	ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*ListTripsResponse, error)
}

type tripsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripsServiceClient(cc grpc.ClientConnInterface) TripsServiceClient {
	return &tripsServiceClient{cc}
}

func (c *tripsServiceClient) ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*ListTripsResponse, error) {
	out := new(ListTripsResponse)
	err := c.cc.Invoke(ctx, "/TripsService/ListTrips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripsServiceServer is the server API for TripsService service.
type TripsServiceServer interface {
	ListTrips(context.Context, *ListTripsRequest) (*ListTripsResponse, error)
}

// UnimplementedTripsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTripsServiceServer struct {
}

func (*UnimplementedTripsServiceServer) ListTrips(context.Context, *ListTripsRequest) (*ListTripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrips not implemented")
}

func RegisterTripsServiceServer(s *grpc.Server, srv TripsServiceServer) {
	s.RegisterService(&_TripsService_serviceDesc, srv)
}

func _TripsService_ListTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripsServiceServer).ListTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TripsService/ListTrips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripsServiceServer).ListTrips(ctx, req.(*ListTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TripsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TripsService",
	HandlerType: (*TripsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTrips",
			Handler:    _TripsService_ListTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detect-presence/proto/trips/trips.proto",
}
